# Data

https://github.com/observablehq/sample-datasets/blob/main/aapl.csv

In [1]:
# Numerical arrays.
import numpy as np

## Reading CSV Files in NumPy

https://numpy.org/doc/stable/user/how-to-io.html

https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html#numpy-loadtxt

In [2]:
# Read data from a CSV using numpy.
data = np.loadtxt("../data/aapl.csv", skiprows=1, delimiter=",", usecols=(1, 2, 3, 4, 5, 6))

# Have a look.
data

array([[6.45014270e+01, 6.54142840e+01, 6.45000000e+01, 6.49628600e+01,
        5.09616280e+01, 7.92372000e+07],
       [6.48357160e+01, 6.50285720e+01, 6.31642880e+01, 6.34085730e+01,
        4.97423290e+01, 1.11779500e+08],
       [6.27371440e+01, 6.30000000e+01, 6.03371430e+01, 6.12642860e+01,
        4.80601880e+01, 1.85403400e+08],
       ...,
       [1.86550003e+02, 1.87399994e+02, 1.85220001e+02, 1.87360001e+02,
        1.86640305e+02, 2.32112000e+07],
       [1.87740005e+02, 1.90369995e+02, 1.87649994e+02, 1.90039993e+02,
        1.89309998e+02, 2.79893000e+07],
       [1.89490005e+02, 1.90059998e+02, 1.87449997e+02, 1.88589996e+02,
        1.88589996e+02, 2.58066000e+07]], shape=(1260, 6))

## Slicing

https://numpy.org/doc/stable/user/absolute_beginners.html#indexing-and-slicing

In [3]:
# The first row.
data[0]

array([6.4501427e+01, 6.5414284e+01, 6.4500000e+01, 6.4962860e+01,
       5.0961628e+01, 7.9237200e+07])

In [4]:
# The first column.
data[:, 0]

array([ 64.501427,  64.835716,  62.737144, ..., 186.550003, 187.740005,
       189.490005], shape=(1260,))

## End